### PR TITLE
Unset tlength if equal to 1 to avoid making 4D minc volumes always

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by matthew-brett** [comment]
Thanks a lot for taking the time to do a PR.  Can you think of a good test to add?

**Comment by gdevenyi** [comment]
I'm guessing that sample/ contains an example dataset I can play with?

I could write a test that uses `mincinfo` to check the dimension count in a resulting minc file after conversion, does that make sense?

**Comment by matthew-brett** [comment]
Thanks for thinking about this.  Yes, I guess you copy `sample.001` to `sample.002` then check that the minc output is what you expect.

**Comment by matthew-brett** [comment]
Sorry - I mean copy and edit the files and then check ....

**Comment by gdevenyi** [comment]
Are you automating these tests in any way? Can I just copy the existing "basic" test and make a minc-like version? I haven't played with perl unit tests before...

**Comment by matthew-brett** [comment]
Well - not completely automated, but the procedure is:

```
perl Makefile.PL
make test
```

I'll try and get that running on travis-ci as well.

**Comment by gdevenyi** [comment]
Cool, that's what I was looking for, looks reasonable.

Travis is super simple, should be no problem installing minc-tools in it for testing.

**Comment by gdevenyi** [comment]
So, it looks like sample.001 doesn't have any data in it's 2dseq files, which breaks rawtominc, which expects _some_ data as an input. So, I can't write any tests yet.

**Comment by gdevenyi** [comment]
Any thoughts on data for tests? I can't run minc tests because of the empty data files.

**Comment by matthew-brett** [comment]
Hum - sorry to be slow to respond.  Do you have any tiny Bruker datasets
you could add?   Anything under about 40k compressed would be fine.​

**Comment by gdevenyi** [comment]
Hrm, my smallest scans are tri-pilots and are way too large for that.

**Comment by matthew-brett** [comment]
What size are your smallest scans?

**Comment by matthew-brett** [comment]
And - actually - you can zero out the data or change it to binary 0 outside brain 1 inside or whatever, in which case they will usually compress down to something small.

**Comment by gdevenyi** [comment]
I have some large ~30MB scans as my smallest right now. I'll ask the MRI operator if he has some smaller scans.

**Comment by gdevenyi** [comment]
I have some fruit data now which is 248kB, will that work?

**Comment by matthew-brett** [comment]
Would you mind adding a license such as http://opendatacommons.org/licenses/pddl for the data, just so people know they can freely re-use?   But yes, sure, go for it.

**Comment by gdevenyi** [comment]
Minc-based tests added, along with example data and licence.

**Comment by matthew-brett** [comment]
Tests fail for me when I don't have minc installed - can you think of a good way to skip the tests when the user doesn't have the minc tools?

**Comment by gdevenyi** [comment]
Looks like I can write some skip code to check for existance of the minc-tools before running tests:
http://perldoc.perl.org/Test.html#Functions

**Comment by gdevenyi** [comment]
I think I've now correctly skipped the tests if minc-toolkit is missing

**Comment by gdevenyi** [comment]
So I think I have this properly fixed now, can you give it a try?

**Comment by gdevenyi** [comment]
After a recent set of tests involving start fmri processing, I found that MINC files didn't have proper information of the timing of the experiment. I have made the additional modification to insert that information.

**Comment by matthew-brett** [comment]
Nice - thanks for your persistence.

**Comment by matthew-brett** [comment]
I edited the `.travis.yml` to use the defaults, added some dependency specifiers.

**Comment by matthew-brett** [comment]
I also added a test where `minc-tools` have been installed, to exercise your MINC test.

**Pull request merged**
